### ISSUE TITLE
Jumping to a chapter in pause mode has no effect

### ISSUE THREAD

**Issue by holgerkrupp** [holgerkrupp/onetrickpony#16]
Thought putting a play() function in the jumping function would solve it. Doesn't solve it. Makes it worse. Don't try it. Bad idea.

**Comment by diodenschein** [comment]
When selecting a chapter the reference to episode gets messed up. It then crashes somewhere after EpisodeViewController:481. Doesn't matter if play or pause. That might be connected.

**Comment by holgerkrupp** [comment]
Hi,

Yeah, I've noticed that yesterday. I'm trying to fix it as soon as I have time (and find a way to fix it)

**Comment by holgerkrupp** [comment]
solved by @diodenschein - thanks a lot.
