### ISSUE TITLE
App crashes when the i Button is tappt

### ISSUE THREAD

**Issue by TimAlber** [holgerkrupp/onetrickpony#41]
In the Episode Play Scene there is the i Button.
It's an i with a circle around it that if tappt should show information about the Episode.
When this Button is tapped, the App crashes.
Maybe my Feed does not include any Episode information but that schuld still not result in a crash. There should be a popup telling the user that there is no information given.

**Comment by holgerkrupp** [comment]
fixed with commit 751f6b048662385a702745df9955356f98c75cb0
